name: immobilierApp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  provider: ^4.3.1
  get_it: ^4.0.2
  url_launcher: ^5.5.0
  flutter_icons: ^1.1.0
  injectable:
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.18.0
  json_annotation: ^3.0.1
  meta: ^1.1.8
  http:
  logger: ^0.9.1
  shared_preferences: ^0.5.8
  path_provider: ^1.6.7
  sembast: ^2.4.3
  modal_bottom_sheet: ^0.2.0+1

dev_dependencies:
  build_runner:
  freezed: ^0.1.3+1
  injectable_generator:
  json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Bold.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/Poppins-Regular.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/key.png
    - assets/contact.png
    - assets/jsonFiles/Categories.json
    - assets/images/farm.png
    - assets/images/appartement.png
    - assets/images/commerce.png
    - assets/images/factory.png
    - assets/images/house.png
    - assets/images/dropDownMenu.png
    - assets/images/house.jpg
    - assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
